server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  datasource:
    platform: postgres
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/school
